server:
  run-mode: test
  http-port: 8080
  read-timeout: 60
  write-timeout: 60

database:
  type: mysql
  user: www
  password: 123
  host: localhost:3306
  name: mail-sender-pool
  table-prefix: msp
log:
  # log-file-path: ./server.log
  slack-token: xoxp-120932188502-630813778544-1412241467106-73b7e89c86f44e3c66d8378cb6f74db5
